#!/bin/bash

java -jar top/target/${rootArtifactId}_top-1.0-SNAPSHOT.jar db drop-all --confirm-delete-everything top/src/main/resources/config.yml
java -jar top/target/${rootArtifactId}_top-1.0-SNAPSHOT.jar db migrate top/src/main/resources/config.yml
java -jar top/target/${rootArtifactId}_top-1.0-SNAPSHOT.jar refdata top/src/main/resources/config.yml
